#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuanLyChungCu
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QuanLyChungCu")]
	public partial class DataLinqDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCanHo(CanHo instance);
    partial void UpdateCanHo(CanHo instance);
    partial void DeleteCanHo(CanHo instance);
    partial void InsertUserLogin(UserLogin instance);
    partial void UpdateUserLogin(UserLogin instance);
    partial void DeleteUserLogin(UserLogin instance);
    partial void InsertCanHo_DichVu(CanHo_DichVu instance);
    partial void UpdateCanHo_DichVu(CanHo_DichVu instance);
    partial void DeleteCanHo_DichVu(CanHo_DichVu instance);
    partial void InsertChucVu(ChucVu instance);
    partial void UpdateChucVu(ChucVu instance);
    partial void DeleteChucVu(ChucVu instance);
    partial void InsertDichVu(DichVu instance);
    partial void UpdateDichVu(DichVu instance);
    partial void DeleteDichVu(DichVu instance);
    partial void InsertNguoiDan(NguoiDan instance);
    partial void UpdateNguoiDan(NguoiDan instance);
    partial void DeleteNguoiDan(NguoiDan instance);
    partial void InsertNhanVien(NhanVien instance);
    partial void UpdateNhanVien(NhanVien instance);
    partial void DeleteNhanVien(NhanVien instance);
    partial void InsertSoHuuCanHo(SoHuuCanHo instance);
    partial void UpdateSoHuuCanHo(SoHuuCanHo instance);
    partial void DeleteSoHuuCanHo(SoHuuCanHo instance);
    #endregion
		
		public DataLinqDataContext() : 
				base(global::QuanLyChungCu.Properties.Settings.Default.QuanLyChungCuConnectionString2, mappingSource)
		{
			OnCreated();
		}
		
		public DataLinqDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLinqDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLinqDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataLinqDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CanHo> CanHos
		{
			get
			{
				return this.GetTable<CanHo>();
			}
		}
		
		public System.Data.Linq.Table<UserLogin> UserLogins
		{
			get
			{
				return this.GetTable<UserLogin>();
			}
		}
		
		public System.Data.Linq.Table<CanHo_DichVu> CanHo_DichVus
		{
			get
			{
				return this.GetTable<CanHo_DichVu>();
			}
		}
		
		public System.Data.Linq.Table<ChucVu> ChucVus
		{
			get
			{
				return this.GetTable<ChucVu>();
			}
		}
		
		public System.Data.Linq.Table<DichVu> DichVus
		{
			get
			{
				return this.GetTable<DichVu>();
			}
		}
		
		public System.Data.Linq.Table<NguoiDan> NguoiDans
		{
			get
			{
				return this.GetTable<NguoiDan>();
			}
		}
		
		public System.Data.Linq.Table<NhanVien> NhanViens
		{
			get
			{
				return this.GetTable<NhanVien>();
			}
		}
		
		public System.Data.Linq.Table<SoHuuCanHo> SoHuuCanHos
		{
			get
			{
				return this.GetTable<SoHuuCanHo>();
			}
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.layDanhSachCanHo", IsComposable=true)]
		public IQueryable<layDanhSachCanHoResult> layDanhSachCanHo()
		{
			return this.CreateMethodCallQuery<layDanhSachCanHoResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.layDanhSachNguoiDan", IsComposable=true)]
		public IQueryable<layDanhSachNguoiDanResult> layDanhSachNguoiDan()
		{
			return this.CreateMethodCallQuery<layDanhSachNguoiDanResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.layDanhSachQuanLyNguoiDan", IsComposable=true)]
		public IQueryable<layDanhSachQuanLyNguoiDanResult> layDanhSachQuanLyNguoiDan()
		{
			return this.CreateMethodCallQuery<layDanhSachQuanLyNguoiDanResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.themNguoiDan")]
		public int themNguoiDan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string ma, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(30)")] string ten, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string gioitinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaysinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string dantoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string tongiao, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(30)")] string nghenghiep, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string sodienthoai, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string macanho)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma, ten, gioitinh, ngaysinh, dantoc, tongiao, nghenghiep, sodienthoai, macanho);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.laySoTang", IsComposable=true)]
		public System.Nullable<int> laySoTang()
		{
			return ((System.Nullable<int>)(this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod()))).ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.layDanhSachCanHoTheoTang", IsComposable=true)]
		public IQueryable<layDanhSachCanHoTheoTangResult> layDanhSachCanHoTheoTang([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tang)
		{
			return this.CreateMethodCallQuery<layDanhSachCanHoTheoTangResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), tang);
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.capNhatNguoiDan")]
		public int capNhatNguoiDan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string ma, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(30)")] string ten, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string gioitinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaysinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string dantoc, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(20)")] string tongiao, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(30)")] string nghenghiep, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string sodienthoai, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string macanho)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma, ten, gioitinh, ngaysinh, dantoc, tongiao, nghenghiep, sodienthoai, macanho);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoaNguoiDan")]
		public int xoaNguoiDan([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string ma)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.layDanhSachCanHoVaChuSoHuu", IsComposable=true)]
		public IQueryable<layDanhSachCanHoVaChuSoHuuResult> layDanhSachCanHoVaChuSoHuu()
		{
			return this.CreateMethodCallQuery<layDanhSachCanHoVaChuSoHuuResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoaCanHo")]
		public int xoaCanHo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string ma)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.themCanHo")]
		public int themCanHo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string ma, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> songuoitoida, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string machusohuu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma, tang, songuoitoida, machusohuu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.capNhatCanHo")]
		public int capNhatCanHo([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string ma, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> tang, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> songuoitoida, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string machusohuu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma, tang, songuoitoida, machusohuu);
			return ((int)(result.ReturnValue));
		}
		
<<<<<<< HEAD
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.themNhanVien")]
		public int themNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string ma, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(30)")] string ten, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string gioitinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaysinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(30)")] string diachi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string sdt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string maquanli, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string machucvu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma, ten, gioitinh, ngaysinh, diachi, sdt, maquanli, machucvu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.capnhapNhanVien")]
		public int capnhapNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string ma, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(30)")] string ten, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string gioitinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Date")] System.Nullable<System.DateTime> ngaysinh, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(30)")] string diachi, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string sdt, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string maquanli, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string machucvu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma, ten, gioitinh, ngaysinh, diachi, sdt, maquanli, machucvu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoaNhanVien")]
		public int xoaNhanVien([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string ma)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), ma);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.layDanhSachNhanVien", IsComposable=true)]
		public IQueryable<layDanhSachNhanVienResult> layDanhSachNhanVien()
		{
			return this.CreateMethodCallQuery<layDanhSachNhanVienResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
=======
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.layDanhSachCanHoDichVu", IsComposable=true)]
		public IQueryable<layDanhSachCanHoDichVuResult> layDanhSachCanHoDichVu()
		{
			return this.CreateMethodCallQuery<layDanhSachCanHoDichVuResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.xoaCanHoDichVu")]
		public int xoaCanHoDichVu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string maCanHo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string maDichVu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCanHo, maDichVu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.capNhatCanHoDichVu")]
		public int capNhatCanHoDichVu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string maCanHo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string maDichVu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCanHo, maDichVu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.themCanHoDichVu")]
		public int themCanHoDichVu([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string maCanHo, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="NChar(10)")] string maDichVu)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), maCanHo, maDichVu);
			return ((int)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.layDanhSachDichVu", IsComposable=true)]
		public IQueryable<layDanhSachDichVuResult> layDanhSachDichVu()
		{
			return this.CreateMethodCallQuery<layDanhSachDichVuResult>(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())));
>>>>>>> 0f7cfdd805726c7e42d8ad0312d6ea6fbc5d1ae0
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CanHo")]
	public partial class CanHo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ma;
		
		private int _tang;
		
		private int _songuoiotoida;
		
		private EntitySet<CanHo_DichVu> _CanHo_DichVus;
		
		private EntitySet<NguoiDan> _NguoiDans;
		
		private EntitySet<SoHuuCanHo> _SoHuuCanHos;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaChanging(string value);
    partial void OnmaChanged();
    partial void OntangChanging(int value);
    partial void OntangChanged();
    partial void OnsonguoiotoidaChanging(int value);
    partial void OnsonguoiotoidaChanged();
    #endregion
		
		public CanHo()
		{
			this._CanHo_DichVus = new EntitySet<CanHo_DichVu>(new Action<CanHo_DichVu>(this.attach_CanHo_DichVus), new Action<CanHo_DichVu>(this.detach_CanHo_DichVus));
			this._NguoiDans = new EntitySet<NguoiDan>(new Action<NguoiDan>(this.attach_NguoiDans), new Action<NguoiDan>(this.detach_NguoiDans));
			this._SoHuuCanHos = new EntitySet<SoHuuCanHo>(new Action<SoHuuCanHo>(this.attach_SoHuuCanHos), new Action<SoHuuCanHo>(this.detach_SoHuuCanHos));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ma
		{
			get
			{
				return this._ma;
			}
			set
			{
				if ((this._ma != value))
				{
					this.OnmaChanging(value);
					this.SendPropertyChanging();
					this._ma = value;
					this.SendPropertyChanged("ma");
					this.OnmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tang", DbType="Int NOT NULL")]
		public int tang
		{
			get
			{
				return this._tang;
			}
			set
			{
				if ((this._tang != value))
				{
					this.OntangChanging(value);
					this.SendPropertyChanging();
					this._tang = value;
					this.SendPropertyChanged("tang");
					this.OntangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_songuoiotoida", DbType="Int NOT NULL")]
		public int songuoiotoida
		{
			get
			{
				return this._songuoiotoida;
			}
			set
			{
				if ((this._songuoiotoida != value))
				{
					this.OnsonguoiotoidaChanging(value);
					this.SendPropertyChanging();
					this._songuoiotoida = value;
					this.SendPropertyChanged("songuoiotoida");
					this.OnsonguoiotoidaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CanHo_CanHo_DichVu", Storage="_CanHo_DichVus", ThisKey="ma", OtherKey="macanho")]
		public EntitySet<CanHo_DichVu> CanHo_DichVus
		{
			get
			{
				return this._CanHo_DichVus;
			}
			set
			{
				this._CanHo_DichVus.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CanHo_NguoiDan", Storage="_NguoiDans", ThisKey="ma", OtherKey="macanho")]
		public EntitySet<NguoiDan> NguoiDans
		{
			get
			{
				return this._NguoiDans;
			}
			set
			{
				this._NguoiDans.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CanHo_SoHuuCanHo", Storage="_SoHuuCanHos", ThisKey="ma", OtherKey="macanho")]
		public EntitySet<SoHuuCanHo> SoHuuCanHos
		{
			get
			{
				return this._SoHuuCanHos;
			}
			set
			{
				this._SoHuuCanHos.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CanHo_DichVus(CanHo_DichVu entity)
		{
			this.SendPropertyChanging();
			entity.CanHo = this;
		}
		
		private void detach_CanHo_DichVus(CanHo_DichVu entity)
		{
			this.SendPropertyChanging();
			entity.CanHo = null;
		}
		
		private void attach_NguoiDans(NguoiDan entity)
		{
			this.SendPropertyChanging();
			entity.CanHo = this;
		}
		
		private void detach_NguoiDans(NguoiDan entity)
		{
			this.SendPropertyChanging();
			entity.CanHo = null;
		}
		
		private void attach_SoHuuCanHos(SoHuuCanHo entity)
		{
			this.SendPropertyChanging();
			entity.CanHo = this;
		}
		
		private void detach_SoHuuCanHos(SoHuuCanHo entity)
		{
			this.SendPropertyChanging();
			entity.CanHo = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.UserLogin")]
	public partial class UserLogin : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ma;
		
		private string _tendangnhap;
		
		private string _matkhau;
		
		private string _quyen;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaChanging(string value);
    partial void OnmaChanged();
    partial void OntendangnhapChanging(string value);
    partial void OntendangnhapChanged();
    partial void OnmatkhauChanging(string value);
    partial void OnmatkhauChanged();
    partial void OnquyenChanging(string value);
    partial void OnquyenChanged();
    #endregion
		
		public UserLogin()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ma
		{
			get
			{
				return this._ma;
			}
			set
			{
				if ((this._ma != value))
				{
					this.OnmaChanging(value);
					this.SendPropertyChanging();
					this._ma = value;
					this.SendPropertyChanged("ma");
					this.OnmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tendangnhap", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string tendangnhap
		{
			get
			{
				return this._tendangnhap;
			}
			set
			{
				if ((this._tendangnhap != value))
				{
					this.OntendangnhapChanging(value);
					this.SendPropertyChanging();
					this._tendangnhap = value;
					this.SendPropertyChanged("tendangnhap");
					this.OntendangnhapChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_matkhau", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string matkhau
		{
			get
			{
				return this._matkhau;
			}
			set
			{
				if ((this._matkhau != value))
				{
					this.OnmatkhauChanging(value);
					this.SendPropertyChanging();
					this._matkhau = value;
					this.SendPropertyChanged("matkhau");
					this.OnmatkhauChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_quyen", DbType="NChar(10)")]
		public string quyen
		{
			get
			{
				return this._quyen;
			}
			set
			{
				if ((this._quyen != value))
				{
					this.OnquyenChanging(value);
					this.SendPropertyChanging();
					this._quyen = value;
					this.SendPropertyChanged("quyen");
					this.OnquyenChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CanHo_DichVu")]
	public partial class CanHo_DichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _macanho;
		
		private string _madichvu;
		
		private EntityRef<CanHo> _CanHo;
		
		private EntityRef<DichVu> _DichVu;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmacanhoChanging(string value);
    partial void OnmacanhoChanged();
    partial void OnmadichvuChanging(string value);
    partial void OnmadichvuChanged();
    #endregion
		
		public CanHo_DichVu()
		{
			this._CanHo = default(EntityRef<CanHo>);
			this._DichVu = default(EntityRef<DichVu>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macanho", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string macanho
		{
			get
			{
				return this._macanho;
			}
			set
			{
				if ((this._macanho != value))
				{
					if (this._CanHo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmacanhoChanging(value);
					this.SendPropertyChanging();
					this._macanho = value;
					this.SendPropertyChanged("macanho");
					this.OnmacanhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_madichvu", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string madichvu
		{
			get
			{
				return this._madichvu;
			}
			set
			{
				if ((this._madichvu != value))
				{
					if (this._DichVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmadichvuChanging(value);
					this.SendPropertyChanging();
					this._madichvu = value;
					this.SendPropertyChanged("madichvu");
					this.OnmadichvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CanHo_CanHo_DichVu", Storage="_CanHo", ThisKey="macanho", OtherKey="ma", IsForeignKey=true)]
		public CanHo CanHo
		{
			get
			{
				return this._CanHo.Entity;
			}
			set
			{
				CanHo previousValue = this._CanHo.Entity;
				if (((previousValue != value) 
							|| (this._CanHo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CanHo.Entity = null;
						previousValue.CanHo_DichVus.Remove(this);
					}
					this._CanHo.Entity = value;
					if ((value != null))
					{
						value.CanHo_DichVus.Add(this);
						this._macanho = value.ma;
					}
					else
					{
						this._macanho = default(string);
					}
					this.SendPropertyChanged("CanHo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu_CanHo_DichVu", Storage="_DichVu", ThisKey="madichvu", OtherKey="ma", IsForeignKey=true)]
		public DichVu DichVu
		{
			get
			{
				return this._DichVu.Entity;
			}
			set
			{
				DichVu previousValue = this._DichVu.Entity;
				if (((previousValue != value) 
							|| (this._DichVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._DichVu.Entity = null;
						previousValue.CanHo_DichVus.Remove(this);
					}
					this._DichVu.Entity = value;
					if ((value != null))
					{
						value.CanHo_DichVus.Add(this);
						this._madichvu = value.ma;
					}
					else
					{
						this._madichvu = default(string);
					}
					this.SendPropertyChanged("DichVu");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.ChucVu")]
	public partial class ChucVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _machucvu;
		
		private string _tenchucvu;
		
		private System.Nullable<decimal> _luong;
		
		private EntitySet<NhanVien> _NhanViens;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmachucvuChanging(string value);
    partial void OnmachucvuChanged();
    partial void OntenchucvuChanging(string value);
    partial void OntenchucvuChanged();
    partial void OnluongChanging(System.Nullable<decimal> value);
    partial void OnluongChanged();
    #endregion
		
		public ChucVu()
		{
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machucvu", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string machucvu
		{
			get
			{
				return this._machucvu;
			}
			set
			{
				if ((this._machucvu != value))
				{
					this.OnmachucvuChanging(value);
					this.SendPropertyChanging();
					this._machucvu = value;
					this.SendPropertyChanged("machucvu");
					this.OnmachucvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tenchucvu", DbType="NChar(30)")]
		public string tenchucvu
		{
			get
			{
				return this._tenchucvu;
			}
			set
			{
				if ((this._tenchucvu != value))
				{
					this.OntenchucvuChanging(value);
					this.SendPropertyChanging();
					this._tenchucvu = value;
					this.SendPropertyChanged("tenchucvu");
					this.OntenchucvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_luong", DbType="Money")]
		public System.Nullable<decimal> luong
		{
			get
			{
				return this._luong;
			}
			set
			{
				if ((this._luong != value))
				{
					this.OnluongChanging(value);
					this.SendPropertyChanging();
					this._luong = value;
					this.SendPropertyChanged("luong");
					this.OnluongChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_NhanVien", Storage="_NhanViens", ThisKey="machucvu", OtherKey="machucvu")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.ChucVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.DichVu")]
	public partial class DichVu : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ma;
		
		private string _ten;
		
		private decimal _chiphi;
		
		private EntitySet<CanHo_DichVu> _CanHo_DichVus;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaChanging(string value);
    partial void OnmaChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OnchiphiChanging(decimal value);
    partial void OnchiphiChanged();
    #endregion
		
		public DichVu()
		{
			this._CanHo_DichVus = new EntitySet<CanHo_DichVu>(new Action<CanHo_DichVu>(this.attach_CanHo_DichVus), new Action<CanHo_DichVu>(this.detach_CanHo_DichVus));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ma
		{
			get
			{
				return this._ma;
			}
			set
			{
				if ((this._ma != value))
				{
					this.OnmaChanging(value);
					this.SendPropertyChanging();
					this._ma = value;
					this.SendPropertyChanged("ma");
					this.OnmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chiphi", DbType="Money NOT NULL")]
		public decimal chiphi
		{
			get
			{
				return this._chiphi;
			}
			set
			{
				if ((this._chiphi != value))
				{
					this.OnchiphiChanging(value);
					this.SendPropertyChanging();
					this._chiphi = value;
					this.SendPropertyChanged("chiphi");
					this.OnchiphiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="DichVu_CanHo_DichVu", Storage="_CanHo_DichVus", ThisKey="ma", OtherKey="madichvu")]
		public EntitySet<CanHo_DichVu> CanHo_DichVus
		{
			get
			{
				return this._CanHo_DichVus;
			}
			set
			{
				this._CanHo_DichVus.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_CanHo_DichVus(CanHo_DichVu entity)
		{
			this.SendPropertyChanging();
			entity.DichVu = this;
		}
		
		private void detach_CanHo_DichVus(CanHo_DichVu entity)
		{
			this.SendPropertyChanging();
			entity.DichVu = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NguoiDan")]
	public partial class NguoiDan : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ma;
		
		private string _ten;
		
		private string _gioitinh;
		
		private System.DateTime _ngaysinh;
		
		private string _dantoc;
		
		private string _tongiao;
		
		private string _nghenghiep;
		
		private string _sodienthoai;
		
		private string _macanho;
		
		private EntitySet<SoHuuCanHo> _SoHuuCanHos;
		
		private EntityRef<CanHo> _CanHo;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaChanging(string value);
    partial void OnmaChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnngaysinhChanging(System.DateTime value);
    partial void OnngaysinhChanged();
    partial void OndantocChanging(string value);
    partial void OndantocChanged();
    partial void OntongiaoChanging(string value);
    partial void OntongiaoChanged();
    partial void OnnghenghiepChanging(string value);
    partial void OnnghenghiepChanged();
    partial void OnsodienthoaiChanging(string value);
    partial void OnsodienthoaiChanged();
    partial void OnmacanhoChanging(string value);
    partial void OnmacanhoChanged();
    #endregion
		
		public NguoiDan()
		{
			this._SoHuuCanHos = new EntitySet<SoHuuCanHo>(new Action<SoHuuCanHo>(this.attach_SoHuuCanHos), new Action<SoHuuCanHo>(this.detach_SoHuuCanHos));
			this._CanHo = default(EntityRef<CanHo>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ma
		{
			get
			{
				return this._ma;
			}
			set
			{
				if ((this._ma != value))
				{
					this.OnmaChanging(value);
					this.SendPropertyChanging();
					this._ma = value;
					this.SendPropertyChanged("ma");
					this.OnmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date NOT NULL")]
		public System.DateTime ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dantoc", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string dantoc
		{
			get
			{
				return this._dantoc;
			}
			set
			{
				if ((this._dantoc != value))
				{
					this.OndantocChanging(value);
					this.SendPropertyChanging();
					this._dantoc = value;
					this.SendPropertyChanged("dantoc");
					this.OndantocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongiao", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string tongiao
		{
			get
			{
				return this._tongiao;
			}
			set
			{
				if ((this._tongiao != value))
				{
					this.OntongiaoChanging(value);
					this.SendPropertyChanging();
					this._tongiao = value;
					this.SendPropertyChanged("tongiao");
					this.OntongiaoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nghenghiep", DbType="NChar(30)")]
		public string nghenghiep
		{
			get
			{
				return this._nghenghiep;
			}
			set
			{
				if ((this._nghenghiep != value))
				{
					this.OnnghenghiepChanging(value);
					this.SendPropertyChanging();
					this._nghenghiep = value;
					this.SendPropertyChanged("nghenghiep");
					this.OnnghenghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthoai", DbType="NChar(10)")]
		public string sodienthoai
		{
			get
			{
				return this._sodienthoai;
			}
			set
			{
				if ((this._sodienthoai != value))
				{
					this.OnsodienthoaiChanging(value);
					this.SendPropertyChanging();
					this._sodienthoai = value;
					this.SendPropertyChanged("sodienthoai");
					this.OnsodienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macanho", DbType="NChar(10)")]
		public string macanho
		{
			get
			{
				return this._macanho;
			}
			set
			{
				if ((this._macanho != value))
				{
					if (this._CanHo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmacanhoChanging(value);
					this.SendPropertyChanging();
					this._macanho = value;
					this.SendPropertyChanged("macanho");
					this.OnmacanhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDan_SoHuuCanHo", Storage="_SoHuuCanHos", ThisKey="ma", OtherKey="machuho")]
		public EntitySet<SoHuuCanHo> SoHuuCanHos
		{
			get
			{
				return this._SoHuuCanHos;
			}
			set
			{
				this._SoHuuCanHos.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CanHo_NguoiDan", Storage="_CanHo", ThisKey="macanho", OtherKey="ma", IsForeignKey=true)]
		public CanHo CanHo
		{
			get
			{
				return this._CanHo.Entity;
			}
			set
			{
				CanHo previousValue = this._CanHo.Entity;
				if (((previousValue != value) 
							|| (this._CanHo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CanHo.Entity = null;
						previousValue.NguoiDans.Remove(this);
					}
					this._CanHo.Entity = value;
					if ((value != null))
					{
						value.NguoiDans.Add(this);
						this._macanho = value.ma;
					}
					else
					{
						this._macanho = default(string);
					}
					this.SendPropertyChanged("CanHo");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_SoHuuCanHos(SoHuuCanHo entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDan = this;
		}
		
		private void detach_SoHuuCanHos(SoHuuCanHo entity)
		{
			this.SendPropertyChanging();
			entity.NguoiDan = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.NhanVien")]
	public partial class NhanVien : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _ma;
		
		private string _ten;
		
		private string _gioitinh;
		
		private System.DateTime _ngaysinh;
		
		private string _diachi;
		
		private string _sodienthoai;
		
		private string _maquanly;
		
		private string _machucvu;
		
		private EntitySet<NhanVien> _NhanViens;
		
		private EntityRef<ChucVu> _ChucVu;
		
		private EntityRef<NhanVien> _NhanVien1;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmaChanging(string value);
    partial void OnmaChanged();
    partial void OntenChanging(string value);
    partial void OntenChanged();
    partial void OngioitinhChanging(string value);
    partial void OngioitinhChanged();
    partial void OnngaysinhChanging(System.DateTime value);
    partial void OnngaysinhChanged();
    partial void OndiachiChanging(string value);
    partial void OndiachiChanged();
    partial void OnsodienthoaiChanging(string value);
    partial void OnsodienthoaiChanged();
    partial void OnmaquanlyChanging(string value);
    partial void OnmaquanlyChanged();
    partial void OnmachucvuChanging(string value);
    partial void OnmachucvuChanged();
    #endregion
		
		public NhanVien()
		{
			this._NhanViens = new EntitySet<NhanVien>(new Action<NhanVien>(this.attach_NhanViens), new Action<NhanVien>(this.detach_NhanViens));
			this._ChucVu = default(EntityRef<ChucVu>);
			this._NhanVien1 = default(EntityRef<NhanVien>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ma
		{
			get
			{
				return this._ma;
			}
			set
			{
				if ((this._ma != value))
				{
					this.OnmaChanging(value);
					this.SendPropertyChanging();
					this._ma = value;
					this.SendPropertyChanged("ma");
					this.OnmaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this.OntenChanging(value);
					this.SendPropertyChanging();
					this._ten = value;
					this.SendPropertyChanged("ten");
					this.OntenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this.OngioitinhChanging(value);
					this.SendPropertyChanging();
					this._gioitinh = value;
					this.SendPropertyChanged("gioitinh");
					this.OngioitinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date NOT NULL")]
		public System.DateTime ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this.OnngaysinhChanging(value);
					this.SendPropertyChanging();
					this._ngaysinh = value;
					this.SendPropertyChanged("ngaysinh");
					this.OnngaysinhChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this.OndiachiChanging(value);
					this.SendPropertyChanging();
					this._diachi = value;
					this.SendPropertyChanged("diachi");
					this.OndiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthoai", DbType="NChar(10)")]
		public string sodienthoai
		{
			get
			{
				return this._sodienthoai;
			}
			set
			{
				if ((this._sodienthoai != value))
				{
					this.OnsodienthoaiChanging(value);
					this.SendPropertyChanging();
					this._sodienthoai = value;
					this.SendPropertyChanged("sodienthoai");
					this.OnsodienthoaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maquanly", DbType="NChar(10)")]
		public string maquanly
		{
			get
			{
				return this._maquanly;
			}
			set
			{
				if ((this._maquanly != value))
				{
					if (this._NhanVien1.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmaquanlyChanging(value);
					this.SendPropertyChanging();
					this._maquanly = value;
					this.SendPropertyChanged("maquanly");
					this.OnmaquanlyChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machucvu", DbType="NChar(10)")]
		public string machucvu
		{
			get
			{
				return this._machucvu;
			}
			set
			{
				if ((this._machucvu != value))
				{
					if (this._ChucVu.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmachucvuChanging(value);
					this.SendPropertyChanging();
					this._machucvu = value;
					this.SendPropertyChanged("machucvu");
					this.OnmachucvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_NhanVien", Storage="_NhanViens", ThisKey="ma", OtherKey="maquanly")]
		public EntitySet<NhanVien> NhanViens
		{
			get
			{
				return this._NhanViens;
			}
			set
			{
				this._NhanViens.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="ChucVu_NhanVien", Storage="_ChucVu", ThisKey="machucvu", OtherKey="machucvu", IsForeignKey=true)]
		public ChucVu ChucVu
		{
			get
			{
				return this._ChucVu.Entity;
			}
			set
			{
				ChucVu previousValue = this._ChucVu.Entity;
				if (((previousValue != value) 
							|| (this._ChucVu.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._ChucVu.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._ChucVu.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._machucvu = value.machucvu;
					}
					else
					{
						this._machucvu = default(string);
					}
					this.SendPropertyChanged("ChucVu");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NhanVien_NhanVien", Storage="_NhanVien1", ThisKey="maquanly", OtherKey="ma", IsForeignKey=true)]
		public NhanVien NhanVien1
		{
			get
			{
				return this._NhanVien1.Entity;
			}
			set
			{
				NhanVien previousValue = this._NhanVien1.Entity;
				if (((previousValue != value) 
							|| (this._NhanVien1.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NhanVien1.Entity = null;
						previousValue.NhanViens.Remove(this);
					}
					this._NhanVien1.Entity = value;
					if ((value != null))
					{
						value.NhanViens.Add(this);
						this._maquanly = value.ma;
					}
					else
					{
						this._maquanly = default(string);
					}
					this.SendPropertyChanged("NhanVien1");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien1 = this;
		}
		
		private void detach_NhanViens(NhanVien entity)
		{
			this.SendPropertyChanging();
			entity.NhanVien1 = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.SoHuuCanHo")]
	public partial class SoHuuCanHo : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _machuho;
		
		private string _macanho;
		
		private EntityRef<CanHo> _CanHo;
		
		private EntityRef<NguoiDan> _NguoiDan;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmachuhoChanging(string value);
    partial void OnmachuhoChanged();
    partial void OnmacanhoChanging(string value);
    partial void OnmacanhoChanged();
    #endregion
		
		public SoHuuCanHo()
		{
			this._CanHo = default(EntityRef<CanHo>);
			this._NguoiDan = default(EntityRef<NguoiDan>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machuho", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string machuho
		{
			get
			{
				return this._machuho;
			}
			set
			{
				if ((this._machuho != value))
				{
					if (this._NguoiDan.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmachuhoChanging(value);
					this.SendPropertyChanging();
					this._machuho = value;
					this.SendPropertyChanged("machuho");
					this.OnmachuhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macanho", DbType="NChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string macanho
		{
			get
			{
				return this._macanho;
			}
			set
			{
				if ((this._macanho != value))
				{
					if (this._CanHo.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmacanhoChanging(value);
					this.SendPropertyChanging();
					this._macanho = value;
					this.SendPropertyChanged("macanho");
					this.OnmacanhoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="CanHo_SoHuuCanHo", Storage="_CanHo", ThisKey="macanho", OtherKey="ma", IsForeignKey=true)]
		public CanHo CanHo
		{
			get
			{
				return this._CanHo.Entity;
			}
			set
			{
				CanHo previousValue = this._CanHo.Entity;
				if (((previousValue != value) 
							|| (this._CanHo.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._CanHo.Entity = null;
						previousValue.SoHuuCanHos.Remove(this);
					}
					this._CanHo.Entity = value;
					if ((value != null))
					{
						value.SoHuuCanHos.Add(this);
						this._macanho = value.ma;
					}
					else
					{
						this._macanho = default(string);
					}
					this.SendPropertyChanged("CanHo");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="NguoiDan_SoHuuCanHo", Storage="_NguoiDan", ThisKey="machuho", OtherKey="ma", IsForeignKey=true)]
		public NguoiDan NguoiDan
		{
			get
			{
				return this._NguoiDan.Entity;
			}
			set
			{
				NguoiDan previousValue = this._NguoiDan.Entity;
				if (((previousValue != value) 
							|| (this._NguoiDan.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._NguoiDan.Entity = null;
						previousValue.SoHuuCanHos.Remove(this);
					}
					this._NguoiDan.Entity = value;
					if ((value != null))
					{
						value.SoHuuCanHos.Add(this);
						this._machuho = value.ma;
					}
					else
					{
						this._machuho = default(string);
					}
					this.SendPropertyChanged("NguoiDan");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class layDanhSachCanHoResult
	{
		
		private string _ma;
		
		private int _tang;
		
		private int _songuoiotoida;
		
		public layDanhSachCanHoResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ma
		{
			get
			{
				return this._ma;
			}
			set
			{
				if ((this._ma != value))
				{
					this._ma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tang", DbType="Int NOT NULL")]
		public int tang
		{
			get
			{
				return this._tang;
			}
			set
			{
				if ((this._tang != value))
				{
					this._tang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_songuoiotoida", DbType="Int NOT NULL")]
		public int songuoiotoida
		{
			get
			{
				return this._songuoiotoida;
			}
			set
			{
				if ((this._songuoiotoida != value))
				{
					this._songuoiotoida = value;
				}
			}
		}
	}
	
	public partial class layDanhSachNguoiDanResult
	{
		
		private string _ma;
		
		private string _ten;
		
		private string _gioitinh;
		
		private System.DateTime _ngaysinh;
		
		private string _dantoc;
		
		private string _tongiao;
		
		private string _nghenghiep;
		
		private string _sodienthoai;
		
		public layDanhSachNguoiDanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ma
		{
			get
			{
				return this._ma;
			}
			set
			{
				if ((this._ma != value))
				{
					this._ma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this._ten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this._gioitinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date NOT NULL")]
		public System.DateTime ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this._ngaysinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dantoc", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string dantoc
		{
			get
			{
				return this._dantoc;
			}
			set
			{
				if ((this._dantoc != value))
				{
					this._dantoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongiao", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string tongiao
		{
			get
			{
				return this._tongiao;
			}
			set
			{
				if ((this._tongiao != value))
				{
					this._tongiao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nghenghiep", DbType="NChar(10)")]
		public string nghenghiep
		{
			get
			{
				return this._nghenghiep;
			}
			set
			{
				if ((this._nghenghiep != value))
				{
					this._nghenghiep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthoai", DbType="NChar(10)")]
		public string sodienthoai
		{
			get
			{
				return this._sodienthoai;
			}
			set
			{
				if ((this._sodienthoai != value))
				{
					this._sodienthoai = value;
				}
			}
		}
	}
	
	public partial class layDanhSachQuanLyNguoiDanResult
	{
		
		private string _ma;
		
		private string _ten;
		
		private string _gioitinh;
		
		private System.DateTime _ngaysinh;
		
		private string _dantoc;
		
		private string _tongiao;
		
		private string _nghenghiep;
		
		private string _sodienthoai;
		
		private string _macanho;
		
		private int _tang;
		
		public layDanhSachQuanLyNguoiDanResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ma
		{
			get
			{
				return this._ma;
			}
			set
			{
				if ((this._ma != value))
				{
					this._ma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this._ten = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this._gioitinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date NOT NULL")]
		public System.DateTime ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this._ngaysinh = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_dantoc", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string dantoc
		{
			get
			{
				return this._dantoc;
			}
			set
			{
				if ((this._dantoc != value))
				{
					this._dantoc = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tongiao", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string tongiao
		{
			get
			{
				return this._tongiao;
			}
			set
			{
				if ((this._tongiao != value))
				{
					this._tongiao = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_nghenghiep", DbType="NChar(10)")]
		public string nghenghiep
		{
			get
			{
				return this._nghenghiep;
			}
			set
			{
				if ((this._nghenghiep != value))
				{
					this._nghenghiep = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthoai", DbType="NChar(10)")]
		public string sodienthoai
		{
			get
			{
				return this._sodienthoai;
			}
			set
			{
				if ((this._sodienthoai != value))
				{
					this._sodienthoai = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_macanho", DbType="NChar(10)")]
		public string macanho
		{
			get
			{
				return this._macanho;
			}
			set
			{
				if ((this._macanho != value))
				{
					this._macanho = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tang", DbType="Int NOT NULL")]
		public int tang
		{
			get
			{
				return this._tang;
			}
			set
			{
				if ((this._tang != value))
				{
					this._tang = value;
				}
			}
		}
	}
	
	public partial class layDanhSachCanHoTheoTangResult
	{
		
		private string _ma;
		
		private int _tang;
		
		private int _songuoiotoida;
		
		public layDanhSachCanHoTheoTangResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ma
		{
			get
			{
				return this._ma;
			}
			set
			{
				if ((this._ma != value))
				{
					this._ma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tang", DbType="Int NOT NULL")]
		public int tang
		{
			get
			{
				return this._tang;
			}
			set
			{
				if ((this._tang != value))
				{
					this._tang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_songuoiotoida", DbType="Int NOT NULL")]
		public int songuoiotoida
		{
			get
			{
				return this._songuoiotoida;
			}
			set
			{
				if ((this._songuoiotoida != value))
				{
					this._songuoiotoida = value;
				}
			}
		}
	}
	
	public partial class layDanhSachCanHoVaChuSoHuuResult
	{
		
		private string _ma;
		
		private int _tang;
		
		private int _songuoiotoida;
		
		private string _machuho;
		
		private string _ten;
		
		public layDanhSachCanHoVaChuSoHuuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ma
		{
			get
			{
				return this._ma;
			}
			set
			{
				if ((this._ma != value))
				{
					this._ma = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tang", DbType="Int NOT NULL")]
		public int tang
		{
			get
			{
				return this._tang;
			}
			set
			{
				if ((this._tang != value))
				{
					this._tang = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_songuoiotoida", DbType="Int NOT NULL")]
		public int songuoiotoida
		{
			get
			{
				return this._songuoiotoida;
			}
			set
			{
				if ((this._songuoiotoida != value))
				{
					this._songuoiotoida = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machuho", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string machuho
		{
			get
			{
				return this._machuho;
			}
			set
			{
				if ((this._machuho != value))
				{
					this._machuho = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this._ten = value;
				}
			}
		}
	}
	
<<<<<<< HEAD
	public partial class layDanhSachNhanVienResult
	{
		
		private string _ma;
		
		private string _ten;
		
		private string _gioitinh;
		
		private System.DateTime _ngaysinh;
		
		private string _diachi;
		
		private string _sodienthoai;
		
		private string _maquanly;
		
		private string _machucvu;
		
		public layDanhSachNhanVienResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ma
		{
			get
			{
				return this._ma;
			}
			set
			{
				if ((this._ma != value))
				{
					this._ma = value;
=======
	public partial class layDanhSachCanHoDichVuResult
	{
		
		private string _maCH;
		
		private int _tang;
		
		private string _maDV;
		
		private string _ten;
		
		private System.Nullable<decimal> _chiphi;
		
		public layDanhSachCanHoDichVuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maCH", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string maCH
		{
			get
			{
				return this._maCH;
			}
			set
			{
				if ((this._maCH != value))
				{
					this._maCH = value;
>>>>>>> 0f7cfdd805726c7e42d8ad0312d6ea6fbc5d1ae0
				}
			}
		}
		
<<<<<<< HEAD
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this._ten = value;
=======
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tang", DbType="Int NOT NULL")]
		public int tang
		{
			get
			{
				return this._tang;
			}
			set
			{
				if ((this._tang != value))
				{
					this._tang = value;
>>>>>>> 0f7cfdd805726c7e42d8ad0312d6ea6fbc5d1ae0
				}
			}
		}
		
<<<<<<< HEAD
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_gioitinh", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string gioitinh
		{
			get
			{
				return this._gioitinh;
			}
			set
			{
				if ((this._gioitinh != value))
				{
					this._gioitinh = value;
=======
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maDV", DbType="NChar(10)")]
		public string maDV
		{
			get
			{
				return this._maDV;
			}
			set
			{
				if ((this._maDV != value))
				{
					this._maDV = value;
>>>>>>> 0f7cfdd805726c7e42d8ad0312d6ea6fbc5d1ae0
				}
			}
		}
		
<<<<<<< HEAD
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ngaysinh", DbType="Date NOT NULL")]
		public System.DateTime ngaysinh
		{
			get
			{
				return this._ngaysinh;
			}
			set
			{
				if ((this._ngaysinh != value))
				{
					this._ngaysinh = value;
=======
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NChar(30)")]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this._ten = value;
>>>>>>> 0f7cfdd805726c7e42d8ad0312d6ea6fbc5d1ae0
				}
			}
		}
		
<<<<<<< HEAD
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_diachi", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string diachi
		{
			get
			{
				return this._diachi;
			}
			set
			{
				if ((this._diachi != value))
				{
					this._diachi = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sodienthoai", DbType="NChar(10)")]
		public string sodienthoai
		{
			get
			{
				return this._sodienthoai;
			}
			set
			{
				if ((this._sodienthoai != value))
				{
					this._sodienthoai = value;
=======
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chiphi", DbType="Money")]
		public System.Nullable<decimal> chiphi
		{
			get
			{
				return this._chiphi;
			}
			set
			{
				if ((this._chiphi != value))
				{
					this._chiphi = value;
				}
			}
		}
	}
	
	public partial class layDanhSachDichVuResult
	{
		
		private string _ma;
		
		private string _ten;
		
		private decimal _chiphi;
		
		public layDanhSachDichVuResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ma", DbType="NChar(10) NOT NULL", CanBeNull=false)]
		public string ma
		{
			get
			{
				return this._ma;
			}
			set
			{
				if ((this._ma != value))
				{
					this._ma = value;
>>>>>>> 0f7cfdd805726c7e42d8ad0312d6ea6fbc5d1ae0
				}
			}
		}
		
<<<<<<< HEAD
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_maquanly", DbType="NChar(10)")]
		public string maquanly
		{
			get
			{
				return this._maquanly;
			}
			set
			{
				if ((this._maquanly != value))
				{
					this._maquanly = value;
=======
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ten", DbType="NChar(30) NOT NULL", CanBeNull=false)]
		public string ten
		{
			get
			{
				return this._ten;
			}
			set
			{
				if ((this._ten != value))
				{
					this._ten = value;
>>>>>>> 0f7cfdd805726c7e42d8ad0312d6ea6fbc5d1ae0
				}
			}
		}
		
<<<<<<< HEAD
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_machucvu", DbType="NChar(10)")]
		public string machucvu
		{
			get
			{
				return this._machucvu;
			}
			set
			{
				if ((this._machucvu != value))
				{
					this._machucvu = value;
=======
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_chiphi", DbType="Money NOT NULL")]
		public decimal chiphi
		{
			get
			{
				return this._chiphi;
			}
			set
			{
				if ((this._chiphi != value))
				{
					this._chiphi = value;
>>>>>>> 0f7cfdd805726c7e42d8ad0312d6ea6fbc5d1ae0
				}
			}
		}
	}
}
#pragma warning restore 1591
